name: Speedtest
services:
  Speedtest:
    image: ghcr.io/librespeed/speedtest:5.5.1-alpine
    container_name: Speedtest
    restart: unless-stopped
    hostname: speedtest
    networks:
      - Speedtest
    environment:
      - MODE=standalone
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M

networks:
  Speedtest:
    name: Speedtest
    external: true
